name: Keep Streamlit ‘awake’

on:
  schedule:
    - cron: '*/5 * * * *'  # executa a cada 5 minutos

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -m 10 -s https://seu-app.streamlit.app > /dev/null
